### ISSUE TITLE
Amélioration de la documentation

### ISSUE THREAD

**Issue by quark67** [cmtpages/playcards#1]
Sur la documentation, il y a une erreur sur les options de la commande `\drawcardsrecto`.

Il est écrit : 

> cicleRay (valeur par défaut : 20)

Évidemment, il faut lire circleRay (il manque un "r" : ciRcle, et c'est sur la documentation française et anglaise).

D'autre part, il serait mieux que la documentation comporte des exemple PDF (plutôt que PNG) de ce que produit le package, car cette image : 
<img width="664" alt="image" src="https://user-images.githubusercontent.com/9338576/235517104-fd8fb238-c2e4-40b9-86a8-9f1809075ff9.png">

est plutôt pixellisée.

En théorie, le code : 

```latex
\documentclass[border=1pt]{standalone}
\usepackage{playcards}
\begin{document}
\drawcardsrecto[trame=false]{5}
\end{document}
```

devrait produire un fichier PDF de la carte, qu'il est alors facile d'inclure dans la documentation avec un `\includegraphics` puisque `pdflatex` accepte les fichiers PDF pour les images.

Malheureusement, il y a un problème d'origine des coordonnées (ou de *bounding box* ?) dans l'image produite par l'extension, ce qui résulte en ce résultat décalé (et coupé) : 

<img width="412" alt="image" src="https://user-images.githubusercontent.com/9338576/235518183-e73a3103-dcd1-498f-89c2-e97a7590fc75.png">

D'ailleurs, la classe `standalone` est à peu près la seule qui soit utilisable avec le package, puisque par défaut le package définit une police de caractère très spéciale comme police par défaut (je pense que cela serait bon de le mentionner dans la documentation).

Une suggestion : ne pas changer la police de caractère par défaut lorsque le package est chargé, afin de pouvoir employer le package avec une classe de document plus usuelle comme `article` sans changer drastiquement l'apparence du texte principal (et permettre éventuellement à l'utilisateur de spécifier une fonte particulière pour les inscriptions sur la carte, via une option).

Actuellement, le code (légèrement modifié, provenant de votre documentation) : 

```latex
\documentclass{article}
\usepackage{playcards}
\usepackage{graphicx}
\begin{document}
\begin{figure}[h]\begin{center}
	\caption{\textbackslash drawcardsrecto[trame=false]\{5\}}
	\drawcardsrecto[trame=false]{5}
\end{center}\end{figure}
\end{document}
```

produit ce résultat : 

<img width="482" alt="image" src="https://user-images.githubusercontent.com/9338576/235520536-b02c07b4-ec10-4c8d-a346-9ce2bb0fa663.png">

(j'ai coupé le bas de la carte). Vous noterez que la carte apparait très haut sur la page, bien plus haut que ce que propose la marge supérieure par défaut de la classe article, ce qui démontre bien le problème d'origine des coordonnées ou de *bounding box*  : 

<img width="346" alt="image" src="https://user-images.githubusercontent.com/9338576/235520869-0001fb2f-0f13-440a-b053-a68cfdd46db3.png">

(ici, c'est avec le format de page `letterpaper`, au lieu du traditionnel `a4paper`, mais cela ne change rien fondamentalement).

**Comment by cmtpages** [comment]
Merci pour ce retour.
- Concernant les fautes de frappe, je les ai corrigées quelques heures après la publication, ça sera pour la prochaine release.
- Pour les polices d'écriture, l'idéal serait de pouvoir passer la _font_ en paramètre du package, mais je manque d'expertise. Est-ce que tu as de la doc à ce sujet ? Je suis un peu passé à côté de ce sujet parce que dans l'usage que j'avais imaginé, c'était pour produire systématiquement des cartes dans un document autonome. Avec `DeclareOption`, je n'ai pas réussi à passer un `RequirePackage` en paramètre. Faute de mieux, laisser la police par défaut est probablement la meilleure solution.
[EDIT] J'ai trouvé une solution mais je ne sais pas si elle est propre, cf. 3e97873e4a7aa634864342afb6fd1d7631bb92b3
- Concernant les marges, ça semble lié au fait que je charge `\geometry` avec l'option `scale=0.950`, qui optimise l'occupation d'une page A4. J'ai retiré le package `geometry` ce qui résout le problème des marges. Mais il n'empêche que pour avoir le bon aligement avec `\drawcardsrecto[trame=true]{...}`, il faut régler les marges.
[EDIT] Cf. a2cff6eb98eec835d7c89be61e18871b82ae29e2

Si vous avez des suggestions ou des corrections à apporter, n'hésitez pas à proposer des PR sur la branche `dev`.

**Comment by quark67** [comment]
Il est possible d'envisager de permettre à l'utilisateur de fournir le code de la fonte souhaitée.

```latex
\documentclass{article}
\usepackage{playcards}
\usepackage{arev}
\usepackage{lmodern}
\begin{document}

test % par défaut lmodern (dernier package de fonte serif chargé)

{\fontfamily{phv}\selectfont test} % Helvetica, pas besoin de charger le package "helvet" 
% car c'est une police postscript (je ne connais pas les détails techniques
% qui expliquent cette différence de traitement)

{\fontfamily{fav}\selectfont test} % Arev Sans, avec package "arev"

{\fontfamily{calligra}\selectfont test} % Calligra avec le package "calligra"

{\fontfamily{antt}\selectfont test} % Antykwa Toruńska avec le package "anttor" (via "playcards")

test
\end{document}
```

produit : 

<img width="109" alt="image" src="https://user-images.githubusercontent.com/9338576/235540390-9bf740de-9e47-4fd4-a7b2-c17f25778716.png">

Pour l'obtention du code des fontes, une solution est de charger la fonte  souhaitée via son package de support, le cas échéant de passer en fonte sans serif via `\sffamily` (après`\begin{document}`) et de récupérer le code avec `\f@family`.

Exemple concret : 

```latex
\documentclass{article}
\usepackage{arev}

\begin{document}
\sffamily % car Arev Sans est une fonte sans serif
\makeatletter
le code est \f@family 
\makeatother
\end{document}
```

produit : 

<img width="278" alt="image" src="https://user-images.githubusercontent.com/9338576/235541535-ec3f4b28-e2ae-475a-83b6-0f37a332f8df.png">

Avec `\usepackage{calligra}`, en remplaçant `\sffamily` par `\calligra` (ce qui sélectionne la fonte), on obtient : 

<img width="254" alt="image" src="https://user-images.githubusercontent.com/9338576/235542006-cf4706d2-c1e8-4f06-a0c2-262fa5136eac.png">

Avec `\usepackage{cantarell}` et `\fcafamily` au lieu de `\sffamilty`, on obtient : 

<img width="398" alt="image" src="https://user-images.githubusercontent.com/9338576/235542645-1f2a8a9f-9b82-4214-980c-569df0b26b76.png">

de sorte que : 

```latex
\documentclass{article}
\usepackage{cantarell}

\begin{document}
test

{\fontfamily{cantarell-TLF}\selectfont texte en fonte cantarell}
\end{document}
```

produise : 

<img width="384" alt="image" src="https://user-images.githubusercontent.com/9338576/235542896-207cd5c1-a8d9-40c4-99d9-6c26d6455711.png">

Dans le code précédent, il n'a pas été nécessaire de charger au préalable "lmodern" (ce qui a aussi pour conséquence que le mot "test" est imprimé en Computer modern, la fonte par défaut), car ici le chargement du package "cantarell" ne change pas la fonte par défaut (au contraire des packages "anttor" ou "arev"). La fonte par défaut n'est alors changé qu'après que la commande `\fcafamily` ne soit fournie, ou alors avec `\fontfamily{cantarell-TLF}\selectfont`.

Le monde des fontes est plutôt compliqué (en `pdflatex`) et je suis très loin de tout connaître (et peut-être que j'ai mis des explications maladroites). J'espère néanmoins que ces indications peuvent vous aider.

Quand je disais que le monde des fontes est compliqué : je m'aperçois qu'il n'est même pas nécessaire de charger le package "anttor". Le code suivant : 

```latex
\documentclass{article}

\begin{document}
test

{\fontfamily{antt}\selectfont texte en fonte Antykwa Toruńska}
\end{document}
```

produit : 

<img width="482" alt="image" src="https://user-images.githubusercontent.com/9338576/235544542-17511041-c7a4-413a-966c-d8a2e5bcaf47.png">

Ce qui permet déjà de résoudre un problème : limiter l'envergure de la fonte au dessin des cartes, sans modifier la fonte du texte avant et après les cartes. Donc sans avoir besoin de gérer immédiatement la possibilité pour l'utilisateur final de changer la fonte pour le contenu textuel des cartes, au moins la fonte spécifique des cartes est limitée aux cartes elle-mêmes, en plaçant `\fontfamily{antt}\selectfont texte` dans un groupe `{...}`.

**Comment by cmtpages** [comment]
>  […]
> Ce qui permet déjà de résoudre un problème : limiter l'envergure de la fonte au dessin des cartes, sans modifier la fonte du texte avant et après les cartes. Donc sans avoir besoin de gérer immédiatement la possibilité pour l'utilisateur final de changer la fonte pour le contenu textuel des cartes, au moins la fonte spécifique des cartes est limitée aux cartes elle-mêmes, en plaçant `\fontfamily{antt}\selectfont texte` dans un groupe `{...}`.

N'étant pas non plus un spécialiste des fontes, et ne souhaitant pas passer des (dizaines) d'heures à me documenter, j'ai opté pour ce compromis : ajout d'une option `anttor` au package.
- Si cette option est passée, les cartes sont en Antykwa Toruńska mais le reste du document garde sa police par défaut.
- Si elle ne l'est pas, les cartes gardent la police du document.
Cf. 8ee6949770c9ef9d9de88a6e310b62bd8afeee23

Laisser le choix total de la fonte à l'utilisateur⋅rice expose à des difficultés techniques que je ne suis pas sûr de pouvoir maîtriser.

**Comment by quark67** [comment]
Ok. Par contre, c'est quoi un utilisateur⋅rice ? Vous vouliez écrire sans doute « utilisateur », non ? L'utilisateur pourra effectivement changer individuellement la fonte employée pour les cartes en limitant la portée du changement de fonte en plaçant la commande de création de la carte dans un groupe (au sens LaTeX du terme). Cela est probablement la solution la plus efficace pour tout le monde.

**Comment by cmtpages** [comment]
Merci pour vos contributions. Ne souhaitant pas ouvrir un débat sur la pertinence du point médian pour l'[écriture inclusive en français](https://fr.wikipedia.org/wiki/Langage_inclusif_en_fran%C3%A7ais), je ferme l'_issue_ car je crois avoir traité l'ensemble des éléments signalés.
